import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css"; // Ensure you have a global CSS file

const poppins = Poppins({
  subsets: ["latin"], // You can customize subsets
  weight: ["400", "700"], // Specify weights
  variable: "--font-poppins", // Set a CSS variable
});

import "./globals.css";
import Aside from "./Aside";
import Nav from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <main>
          <Aside />
          <div className="main-content">
            <Nav />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
